/*
   BLACK FRIDAY SALES - DATABASE SETUP & ETL
   NAME: DIPJYOTI KARMAKAR
*/

-- 1. INITIATING & CREATING DATABASE
DROP DATABASE IF EXISTS BLACK_FRIDAY_DB;
CREATE DATABASE BLACK_FRIDAY_DB;
USE BLACK_FRIDAY_DB;

-- ENABLE LOCAL FILE LOADING FOR CSV IMPORT
SET GLOBAL LOCAL_INFILE = 1; 

-- 2. CREATE RAW TABLE
CREATE TABLE BLACK_FRIDAY_DATA (
    USER_ID INT,
    PRODUCT_ID VARCHAR(20),
    GENDER CHAR(1),
    AGE VARCHAR(10),
    OCCUPATION INT,
    CITY_CATEGORY CHAR(1),
    STAY_IN_CURRENT_CITY_YEARS VARCHAR(5),
    MARITAL_STATUS INT,
    PRODUCT_CATEGORY_1 INT,
    PRODUCT_CATEGORY_2 INT, 
    PRODUCT_CATEGORY_3 INT, 
    PURCHASE INT
);

-- 3. LOAD DATA
/* NOTE TO EXAMINER: 
   THE PATH BELOW IS FOR MY LOCAL MACHINE. 
   PLEASE UPDATE IT TO THE LOCATION WHERE YOU SAVED 'BLACK FRIDAY DATA - CSV.CSV'.
   (USE FORWARD SLASHES '/' TO AVOID SYNTAX ERRORS)
*/

LOAD DATA LOCAL INFILE 'C:/Users/HELLO WORLD/OneDrive/Desktop/Project/Career247/Dataset_-_Black_Friday_Sales_Analysis/Black Friday Data - CSV.csv' 
INTO TABLE BLACK_FRIDAY_DATA 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS
(USER_ID, PRODUCT_ID, GENDER, AGE, OCCUPATION, CITY_CATEGORY, STAY_IN_CURRENT_CITY_YEARS, MARITAL_STATUS, PRODUCT_CATEGORY_1, @CAT2, @CAT3, PURCHASE)
SET 
    PRODUCT_CATEGORY_2 = NULLIF(@CAT2, ''), -- CONVERT EMPTY STRINGS TO NULL
    PRODUCT_CATEGORY_3 = NULLIF(@CAT3, '');

-- 4. ADD CONSTRAINTS & PRIMARY KEY
-- DATASET HAS DUPLICATE (USER + PRODUCT) ROWS, SO IT NEEDS A SURROGATE KEY (TRANSACTION_ID)
-- TO PRESERVE PURCHASE HISTORY WITHOUT DATA LOSS.
ALTER TABLE BLACK_FRIDAY_DATA
ADD COLUMN TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY FIRST;

-- ENFORCE DATA QUALITY RULES
ALTER TABLE BLACK_FRIDAY_DATAblack_friday_master
MODIFY COLUMN USER_ID INT NOT NULL,
MODIFY COLUMN PRODUCT_ID VARCHAR(20) NOT NULL,
MODIFY COLUMN PURCHASE INT NOT NULL,
ADD CONSTRAINT CHK_PURCHASE_POSITIVE CHECK (PURCHASE > 0);

-- 5. REPORTING VIEWS
-- CUSTOMER DEMOGRAPHICS
CREATE OR REPLACE VIEW VIEW_CUSTOMER_INFO AS
SELECT DISTINCT USER_ID, GENDER, AGE, OCCUPATION, CITY_CATEGORY, STAY_IN_CURRENT_CITY_YEARS, MARITAL_STATUS
FROM BLACK_FRIDAY_DATA ORDER BY USER_ID;

-- PRODUCT CATALOG
CREATE OR REPLACE VIEW VIEW_PRODUCT_INFO AS
SELECT DISTINCT PRODUCT_ID, PRODUCT_CATEGORY_1, PRODUCT_CATEGORY_2, PRODUCT_CATEGORY_3
FROM BLACK_FRIDAY_DATA ORDER BY PRODUCT_ID;

-- TRANSACTIONS FACT TABLE
CREATE OR REPLACE VIEW VIEW_TRANSACTION_DATA AS
SELECT TRANSACTION_ID, USER_ID, PRODUCT_ID, PURCHASE
FROM BLACK_FRIDAY_DATA;

-- 6: VALIDATION & SANITY CHECKS

-- CHECK A: ROW COUNTS
SELECT COUNT(*) AS TOTAL_ROW_COUNT FROM BLACK_FRIDAY_DATA;

-- CHECK B: SANITY QUERIES (DISTINCT CUSTOMERS & PRODUCTS)
SELECT
    COUNT(DISTINCT USER_ID) AS TOTAL_UNIQUE_CUSTOMERS,
    COUNT(DISTINCT PRODUCT_ID) AS TOTAL_UNIQUE_PRODUCTS
FROM BLACK_FRIDAY_DATA;

-- CHECK C: SPOT-CHECK RANDOM ROWS FOR CORRECTNESS
SELECT * FROM BLACK_FRIDAY_DATA LIMIT 5;

-- CHECK D: VERIFY NULL HANDLING LOGIC
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(PRODUCT_CATEGORY_2) AS VALID_CAT2,
    COUNT(*) - COUNT(PRODUCT_CATEGORY_2) AS NULL_CAT2
FROM BLACK_FRIDAY_DATA;

-- 7. ANALYTICAL CHECKS
-- VALIDATING DATA RELATIONSHIPS WITH A JOIN
-- GOAL: CHECK SPENDING DISTRIBUTION BY GENDER
SELECT
    C.GENDER,
    COUNT(T.TRANSACTION_ID) AS TXN_COUNT,
    SUM(T.PURCHASE) AS TOTAL_SPEND
FROM VIEW_TRANSACTION_DATA T
INNER JOIN VIEW_CUSTOMER_INFO C ON T.USER_ID = C.USER_ID
GROUP BY C.GENDER;